<?php $students = array (
  1 => 
  \Student::__set_state(array(
     'studentId' => '1',
     'firstName' => NULL,
     'lastName' => NULL,
     'gender' => NULL,
     'dateOfBirth' => NULL,
     'address' => NULL,
     'city' => NULL,
     'country' => NULL,
     'tel' => NULL,
  )),
  2 => 
  \Student::__set_state(array(
     'studentId' => '2',
     'firstName' => NULL,
     'lastName' => NULL,
     'gender' => NULL,
     'dateOfBirth' => NULL,
     'address' => NULL,
     'city' => NULL,
     'country' => NULL,
     'tel' => NULL,
  )),
  3 => 
  \Student::__set_state(array(
     'studentId' => '3',
     'firstName' => NULL,
     'lastName' => NULL,
     'gender' => NULL,
     'dateOfBirth' => NULL,
     'address' => NULL,
     'city' => NULL,
     'country' => NULL,
     'tel' => NULL,
  )),
  4 => 
  \Student::__set_state(array(
     'studentId' => '4',
     'firstName' => '1',
     'lastName' => '2',
     'gender' => '3',
     'dateOfBirth' => '4',
     'address' => '5',
     'city' => '6',
     'country' => '7',
     'tel' => '4',
  )),
  5 => 
  \Student::__set_state(array(
     'studentId' => '5',
     'firstName' => '1',
     'lastName' => NULL,
     'gender' => NULL,
     'dateOfBirth' => NULL,
     'address' => NULL,
     'city' => NULL,
     'country' => NULL,
     'tel' => NULL,
  )),
  6 => 
  \Student::__set_state(array(
     'studentId' => '6',
     'firstName' => '1',
     'lastName' => NULL,
     'gender' => NULL,
     'dateOfBirth' => NULL,
     'address' => NULL,
     'city' => NULL,
     'country' => NULL,
     'tel' => NULL,
  )),
  7 => 
  \Student::__set_state(array(
     'studentId' => '7',
     'firstName' => '1',
     'lastName' => NULL,
     'gender' => NULL,
     'dateOfBirth' => NULL,
     'address' => NULL,
     'city' => NULL,
     'country' => NULL,
     'tel' => NULL,
  )),
  8 => 
  \Student::__set_state(array(
     'studentId' => '8',
     'firstName' => 'qs',
     'lastName' => NULL,
     'gender' => NULL,
     'dateOfBirth' => NULL,
     'address' => NULL,
     'city' => NULL,
     'country' => NULL,
     'tel' => NULL,
  )),
  9 => 
  \Student::__set_state(array(
     'studentId' => '9',
     'firstName' => 'qdq',
     'lastName' => 'q',
     'gender' => '',
     'dateOfBirth' => '',
     'address' => 'q',
     'city' => 'q',
     'country' => 'q',
     'tel' => 'q',
  )),
  22 => 
  \Student::__set_state(array(
     'studentId' => '22',
     'firstName' => 'qq',
     'lastName' => 'qq',
     'gender' => '',
     'dateOfBirth' => '',
     'address' => '6',
     'city' => '7',
     'country' => 'Palestinian Authority',
     'tel' => 'q',
  )),
  10 => 
  \Student::__set_state(array(
     'studentId' => '10',
     'firstName' => NULL,
     'lastName' => NULL,
     'gender' => NULL,
     'dateOfBirth' => NULL,
     'address' => NULL,
     'city' => NULL,
     'country' => NULL,
     'tel' => NULL,
  )),
  11 => 
  \Student::__set_state(array(
     'studentId' => '11',
     'firstName' => 'sss',
     'lastName' => 'ahmad',
     'gender' => '',
     'dateOfBirth' => '',
     'address' => 'q',
     'city' => 'q',
     'country' => 'q',
     'tel' => 'q',
  )),
  12 => 
  \Student::__set_state(array(
     'studentId' => '12',
     'firstName' => '12',
     'lastName' => '12',
     'gender' => '1',
     'dateOfBirth' => '12',
     'address' => '12',
     'city' => '12',
     'country' => 'Palestinian Authority',
     'tel' => '12',
  )),
  13 => 
  \Student::__set_state(array(
     'studentId' => '13',
     'firstName' => 'rr',
     'lastName' => '12',
     'gender' => '',
     'dateOfBirth' => NULL,
     'address' => '12',
     'city' => '12',
     'country' => 'Palestinian Authority',
     'tel' => '12',
  )),
);