<?php $students = array (
  1 => 
  \Student::__set_state(array(
     'studentId' => '1',
     'firstName' => NULL,
     'lastName' => NULL,
     'gender' => NULL,
     'dateOfBirth' => NULL,
     'address' => NULL,
     'city' => NULL,
     'country' => NULL,
     'tel' => NULL,
  )),
  2 => 
  \Student::__set_state(array(
     'studentId' => '2',
     'firstName' => 'Qusai',
     'lastName' => 'Iyad',
     'gender' => 'Male',
     'dateOfBirth' => '2000-01-24',
     'address' => '122312',
     'city' => 'Sinjel',
     'country' => 'Palestinian Authority',
     'tel' => '05699',
  )),
  3 => 
  \Student::__set_state(array(
     'studentId' => '3',
     'firstName' => 'ahmad',
     'lastName' => 'jamal',
     'gender' => 'Male',
     'dateOfBirth' => '0003-01-02',
     'address' => '123',
     'city' => '123',
     'country' => '123',
     'tel' => '123',
  )),
  4 => 
  \Student::__set_state(array(
     'studentId' => '4',
     'firstName' => 'ahmad',
     'lastName' => 'jamal',
     'gender' => '',
     'dateOfBirth' => '',
     'address' => '123',
     'city' => '123',
     'country' => '123',
     'tel' => '123',
  )),
  5 => 
  \Student::__set_state(array(
     'studentId' => '5',
     'firstName' => 'roaa',
     'lastName' => 'masalmah',
     'gender' => 'Female',
     'dateOfBirth' => '0002-02-03',
     'address' => 'wa2er',
     'city' => 'Ramallah & Al Bireh',
     'country' => 'Palestinian Authority',
     'tel' => '231',
  )),
  6 => 
  \Student::__set_state(array(
     'studentId' => '6',
     'firstName' => 'qusai',
     'lastName' => 'masalmah',
     'gender' => 'Female',
     'dateOfBirth' => '1221-02-01',
     'address' => 'wa2er',
     'city' => 'Ramallah & Al Bireh',
     'country' => 'Palestinian Authority',
     'tel' => '1',
  )),
  7 => 
  \Student::__set_state(array(
     'studentId' => '7',
     'firstName' => 'ahmad',
     'lastName' => 'jamal',
     'gender' => 'Male',
     'dateOfBirth' => NULL,
     'address' => 'wa2er',
     'city' => 'Ramallah & Al Bireh',
     'country' => 'Palestinian Authority',
     'tel' => '231',
  )),
  11 => 
  \Student::__set_state(array(
     'studentId' => '11',
     'firstName' => 'qusai',
     'lastName' => 'masalmah',
     'gender' => 'Female',
     'dateOfBirth' => '0003-01-02',
     'address' => 'wa2er',
     'city' => 'Ramallah & Al Bireh',
     'country' => 'Palestinian Authority',
     'tel' => '',
  )),
);